#!/usr/bin/env python3
"""docs/roster/top100_players.json -> scripts/roster_data.gd (the game's copy of the top-100).
Only game names go into the game file (real names stay in the research). Looks.* indices are
resolved here so the data is plain numbers:  python3 tools/gen_roster_data.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = json.load(open(os.path.join(root, "docs/roster/top100_players.json"), encoding="utf-8"))
SKIN = {1: 1, 2: 2, 3: 3, 4: 4, 5: 6, 6: 8}
HAIR = {"short_neat": [2, 3], "short_crop": [1], "curls_big": [7], "curls_short": [7], "medium_swept": [4],
        "short_messy": [6], "buzz": [1], "medium_wavy": [6, 13], "long_tied": [10], "long_loose": [9], "bald": [0]}
HAIR_COLOR = {"ginger": 8, "dirty_blond": 5, "dark_brown": 1, "black": 0, "light_brown": 4, "brown": 3, "blond": 6, "none": 0}
BEARD = {"none": 0, "short_beard": 4, "stubble": 1, "full_beard": 5, "moustache": 2}
HEAD = {"none": 0, "cap_fwd": 1, "cap_back": 2, "headband": 3}
ACCENT = {"white": 0, "black": 3, "navy": 4, "blue": 5, "turquoise": 7, "orange": 11, "lime": 9, "dark": 2}
# The three whose real names the game already uses for its fixed opponents (see Opponents.ROSTER).
ALIAS = {2: "zverev", 11: "djokovic", 24: "rublev"}
out = ["class_name RosterData",
       "## The top-100 (docs/roster/top100_players.json, research of 05.10.2026) as the game's data: game names",
       "## only. Generated by tools/gen_roster_data.py - edit the JSON and run it, not this file.",
       "## Per player: rank, tier (S..E), name, short (the surname), country, left (a label: the rig is",
       "## right-handed), one_hand (backhand), height (class), look (Looks keys), alias_of (the fixed",
       "## opponent this one is a twin of: left out of the draw).",
       "", "const PLAYERS := ["]
for p in src:
    r = p["rank"]
    ws = p["headwear"].split(":")
    head = HEAD[ws[0]]
    shirt = (r * 7 + 3) % 16
    look = {"skin": SKIN[p["skin"]], "hair": HAIR[p["hair_style"]][r % len(HAIR[p["hair_style"]])],
            "hair_color": HAIR_COLOR[p["hair_color"]], "beard": BEARD[p["facial_hair"]], "head": head,
            "shirt": shirt, "shorts": [3, 2, 0, 4][r % 4], "accent": ACCENT.get(ws[1], shirt) if len(ws) > 1 else shirt}
    e = {"rank": r, "tier": p["tier"], "name": p["game_name"], "short": p["short"], "country": p["country"],
         "left": p["hand"] == "L", "one_hand": p["backhand"] == "1H", "height": p["height_class"], "look": look}
    if r in ALIAS:
        e["alias_of"] = ALIAS[r]
    out.append("\t" + json.dumps(e, ensure_ascii=False).replace('"left": false', '"left": false').replace(": true", ": true") + ",")
out.append("]")
text = "\n".join(out) + "\n"
open(os.path.join(root, "scripts/roster_data.gd"), "w", encoding="utf-8", newline="\n").write(text)
print("players:", len(src))
